version: '2'

volumes:
  foodhub_mysql:
  foodhub_server:

services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "ERLANGYODAWGHERESACOOKIE"
      RABBITMQ_DEFAULT_USER: "urbanpiper"
      RABBITMQ_DEFAULT_PASS: "urbanpiper"
      RABBITMQ_DEFAULT_VHOST: "uphost"
    ports:
      - "15672:15672"
      - "5672:5672"

  mysql:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: "foodhub_db"
      MYSQL_ROOT_PASSWORD: "Up123pU"
    volumes:
      - foodhub_mysql:/server/
      - .:/etc/mysql/conf.d/
    ports:
      - "3300:3306"

  server:
    build:
     context: .
     dockerfile: Dockerfile
    image: server/image
    volumes:
      - foodhub_server:/server/
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
    environment:
      IN_DOCKER_CONTAINER: "TRUE"
    entrypoint:
      - python3
      - /server/manage.py
      - runserver
      - 0.0.0.0:8000

  celery:
    image: server/image
    environment:
      C_FORCE_ROOT: "TRUE"
      IN_DOCKER_CONTAINER: "TRUE"
    entrypoint:
      - celery
      - -A
      - foodhub
      - worker

  celerybeat:
    image: server/image
    environment:
      IN_DOCKER_CONTAINER: "TRUE"
      C_FORCE_ROOT: "TRUE"
    entrypoint:
      - celery
      - -A
      - foodhub
      - beat
