# Generated by Django 3.1.1 on 2020-09-28 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField()),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('active', models.BooleanField(default=False)),
                ('items', models.ManyToManyField(to='entities.Item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('ACT', 'Active'), ('CAN', 'Cancelled'), ('FIN', 'Finished')], default='ACT', max_length=100)),
                ('items', models.ManyToManyField(to='entities.Item')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.merchant')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.store')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.merchant'),
        ),
    ]
