# Generated by Django 3.1.1 on 2020-09-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20200928_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='store',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='lon',
            field=models.FloatField(blank=True),
        ),
    ]
