# Generated by Django 3.1.1 on 2020-12-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20200930_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
