# Generated by Django 3.1.1 on 2020-12-15 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_item_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='active',
        ),
    ]
