# Generated by Django 3.1.1 on 2020-12-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_remove_item_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
