name: Run Tests

on:
  push:
    branches: master

jobs:
  build_server:
    name: Build Server
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6.9]

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      rabbitmq:
        image: rabbitmq:3.8.9
        env:
          RABBITMQ_DEFAULT_USER: urbanpiper
          RABBITMQ_DEFAULT_PASS: urbanpiper
          RABBITMQ_DEFAULT_VHOST: uphost
        ports:
        - 5672:5672
        options: -e RABBITMQ_ERLANG_COOKIE="COOKIE" -e RABBITMQ_DEFAULT_USER="urbanpiper" -e RABBITMQ_DEFAULT_PASS="urbanpiper" -e RABBITMQ_DEFAULT_VHOST="uphost"
          --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      
      - name: Verify MySQL connection from host
        run: |
          sudo apt-get install -y mysql-client
          mysql --host 127.0.0.1 -uroot -ppassword -e "SHOW DATABASES"
      
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: foodhub/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags:  abhi22ray/foodhub:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
      
      - name: Run Container
        uses: docker://abhi22ray/foodhub
        with:
          entrypoint: pytest
          args: -s -v --no-migrations -n auto

      - name: Run Container
        uses: docker://abhi22ray/foodhub
        with:
          entrypoint: pip3
          args: install -r requirements.txt
            
