name: Codex CI Build

on:
  push:
    branches: [ rayp1 ]
  pull_request:
    branches: [ beta ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: abhi22ray/foodhub
      credentials:
        username: abhi22ray
        password: ${{ secrets.DOCKERHUB_PASSWORD}}
      env:
        IN_DOCKER_CONTAINER: true
        ENV_IS_CI: true
        CI_DB_NAME: tests
        CI_DB_USER: root
        CI_DB_PASS: password
        CI_DB_HOST: mysql
        CI_DB_PORT: 3306
    
    steps:

    - uses: actions/checkout@v2


    - name: Check File 1
      run: |
        ls -al /tmp/


    
    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx1-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-buildx1-
   
 
        

        
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.6.9]
     

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
        - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      rabbitmq:
        image: rabbitmq:3.8.9
        env:
          RABBITMQ_DEFAULT_USER: urbanpiper
          RABBITMQ_DEFAULT_PASS: urbanpiper
          RABBITMQ_DEFAULT_VHOST: uphost
        ports:
        - 5672:5672
        options: -e RABBITMQ_ERLANG_COOKIE="COOKIE" -e RABBITMQ_DEFAULT_USER="urbanpiper" -e RABBITMQ_DEFAULT_PASS="urbanpiper" -e RABBITMQ_DEFAULT_VHOST="uphost"
          --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    

